project: 
  type: website

website: 
  page-navigation: false
  title: "Advent Hymnals" 
  site-url: "https://adventhymnals.org" 
  repo-url: "https://github.com/adventhymnals/v3"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: ""
    center: "&copy; 2018-2023 Gospel Sounders"
  
  sidebar:
    background: "#A87A4E"
    favicon: images/favicon.ico
    pinned: false
    align: center
    tools: 
      - icon: globe
        href: https://gospelsounders.org
        text: "Gospel Sounders"
      - icon: github
        href: https://github.com/adventhymnals
        text: "Advent Hymnals"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: campus-melodies
        text: Campus Melodies
      - href: seventh-day-adventist-hymnal
        text: Seventh-day Adventist Hymnal
      - href: nyimbo-za-kristo
        text: Nyimbo za Kristo
      - href: church-hymnal
        text: Church Hymnal
      - href: wende-nyasaye
        text: Wende Nyasaye
      - href: christ-in-song
        text: Christ in Song
      - href: hymns-and-tunes-1876
        text: Hymns and Tunes 1876
      - href: hymns-and-tunes-1869
        text: Hymns and Tunes 1869
      - href: Hymns-for-Gods-Peculiar-People
        text: Hymns for God’s Peculiar People
      - href: millenial-harp
        text: Millenial Harp
      - href: hymns-for-the-poor-of-the-flock
        text: Hymns for the Poor of the Flock
      - href: blog
        text: Blog
format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: false


filters:
  - include-files.lua
  - quarto

  
